name: CI

on:
  push:
    branches: [main, 'feature/*']
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Node.js ${{ matrix.node }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20] # LTS versions only
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Compile TypeScript
        run: npm run compile

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests (Linux only)
        run: xvfb-run -a npm test
        if: runner.os == 'Linux' && matrix.node == '20'

  publish:
    name: Publish to GitHub Packages
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Package extension
        run: npm run package-extension

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: '*.vsix'

      - name: Attach VSIX to release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.vsix'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: |
          # Configure npm to publish to GitHub Packages
          echo "@johnnyphilology:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          
          # Update package.json for GitHub Packages
          npm pkg set "publishConfig.registry=https://npm.pkg.github.com"
          npm pkg set "name=@johnnyphilology/scribe"
          
          # Publish the package
          npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
